services:
  # API Service
  myapi:
    build: .
    ports:
      - "5050:8080"
    networks:
      - net1
    depends_on:
      - sqlserver
      - rabbitmq
    environment:
      - ConnectionStrings__DefaultConnection=Server=sqlserver,1433;Database=ElectroDB;User Id=sa;Password=@abc123@;TrustServerCertificate=True;
      - DBSettings__DefaultConnection=Server=sqlserver,1433;Database=ElectroDB;User Id=sa;Password=@abc123@;TrustServerCertificate=True;
      - RabbitMQ__ConnectionUri=amqp://guest:guest@rabbitmq:5672

  # SQL Server Database
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    hostname: sqlserver
    networks:
      - net1
    ports:
      - "1433:1433"
    volumes:
      - sqldata:/var/opt/mssql
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=@abc123@

  # RabbitMQ
  rabbitmq:
    image: rabbitmq:3-management
    container_name: myrabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - net1

# Networks
networks:
  net1:

# Volumes
volumes:
  sqldata:
